<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>

<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0" />


<title>Comeback Generator</title>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>


<style>

body {

margin: 0;

padding: 0;

background: black;

width: 320px;

height: 480px;

}


#comeback {

background: yellow;

width: 320px;

height: 480px;

font-size:30px;


}


#comeback span {

 display: block;

 width: 100%;

height: 100%;


}


.on {

background-color: red;

}


.off {

background-color: yellow;

}


</style>


<script type="text/javascript">


function changeColor() {

  $('#comeback span').toggleClass('on');

}

$(document).ready(function() {

  setInterval(changeColor, 500);

});


var inprogress = false;

function getComeback()

{

    switch(window.orientation)

    {

        case -90: case 90:

            $("body").css('width', '480px');

            $("body").css('height', '320px');

            $("#comeback").css('width', '320px');



        break;


        default:

            $("body").css('width', '320px');

            $("body").css('height', '480px');

            $("#comeback").css('width', '320px');

            $("#comeback").css('height', '480px');

    }



if(!inprogress) {

inprogress = true;

$.get('/twitter/comebackgen', {}, function(resp){

$("#content").html(resp);

inprogress = false;

}, 'html');

}

}

window.onload = function() {

getComeback();

}


</script>

</head>

<body onorientationchange="getComeback()">

<div id="comeback"><span id="content"></span></div>

</body>

</html>