<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0" />
        <title>Comeback Generator</title>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
        <style>
            body {
                width: 320px;
                height: 480px;
            }

            #comeback {
                width: 320px;
                font-size:40px;
                font-color: red;
            }
        </style>
        <script>
            function getComeback()
            {
                $.get('/twitter/comebackgen', {}, function(resp){
                    $("#comeback").html(resp);
                }, 'html')
            }
            window.onload = function() {
            	getComeback();
            }
        </script>
    </head>
    <body onorientationchange="getComeback()">
        <div id="comeback"></div>
    </body>
</html>
